name: Compile C Program

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: |
        gcc Mon-projet-C -o programme
